### ISSUE TITLE
Connection problem, NullReferenceException

### ISSUE THREAD

**Issue by viktor-morin** [ume05rw/SharpCifs.Std#18]
Hi!
Im doing following, which I have verifed in Windows that works.
I'm testing this in my UWP application as a part of the Xamarin solution.

```
var serverAddress = @"192.168.1.150\Downloads\"; 
var _fileRepository = new SmbFile($"smb:\\{serverAddress}");
var canRead = _fileRepository.CanRead();
```

I then get following exception inside your code:

> {System.NullReferenceException: Object reference not set to an instance of an object.
>    at SharpCifs.Smb.SmbFile.GetType()
>    at SharpCifs.Smb.SmbFile.CanRead()

**Comment by viktor-morin** [comment]
Closed due to inactivity
