### ISSUE TITLE
SharpCifs.Smb.SmbException: Failed to connect, 0.0.0.0<00>/192.168.0.26  [ 192.168.0.26:1733 --> 192.168.0.26:445 ]

### ISSUE THREAD

**Issue by GambaJo** [ume05rw/SharpCifs.Std#38]
Hi,

I made a folder on my Win10 and configurated a share with credentials for a local windows user. Then I tried to list the files in this share.
This is the exception I get:

```
SharpCifs.Smb.SmbException
  HResult=0x80131620
  Nachricht = Failed to connect, 0.0.0.0<00>/192.168.0.26  [ 192.168.0.26:1733 --> 192.168.0.26:445 ]
  Quelle = SharpCifs.Std
  Stapelüberwachung:
   at SharpCifs.Smb.SmbTransport.Connect()
   at SharpCifs.Smb.SmbTree.TreeConnect(ServerMessageBlock andx, ServerMessageBlock andxResponse)
   at SharpCifs.Smb.SmbFile.DoConnect()
   at SharpCifs.Smb.SmbFile.Connect()
   at SharpCifs.Smb.SmbFile.Connect0()
   at SharpCifs.Smb.SmbFile.GetType()
   at SharpCifs.Smb.SmbFile.DoEnum(List`1 list, Boolean files, String wildcard, Int32 searchAttributes, ISmbFilenameFilter fnf, ISmbFileFilter ff)
   at SharpCifs.Smb.SmbFile.ListFiles(String wildcard, Int32 searchAttributes, ISmbFilenameFilter fnf, ISmbFileFilter ff)
   at SharpCifs.Smb.SmbFile.ListFiles()
   at TestCifs.Program.Main(String[] args) in C:\...:line 13

  Diese Ausnahme wurde ursprünglich von dieser Aufrufliste ausgelöst:
    [Externer Code]

Innere Ausnahme 1:
TransportException: transport closed in negotiate

Innere Ausnahme 2:
TransportException: transport closed in negotiate

Innere Ausnahme 3:
IOException: transport closed in negotiate

```

I tried it with the name of my computer and with the IP. I also turned my local firewall off. But I still get the same exceltion.

Here my code:
```
    class Program
    {
        static void Main(string[] args)
        {
            var auth1 = new NtlmPasswordAuthentication(null, "testtest", "testtest");
            var folder = new SmbFile("smb://192.168.0.26/UncPathTest", auth1);

            foreach (SmbFile item in folder.ListFiles())
            {
                Console.WriteLine(item.GetName());
            }

            Console.WriteLine("This is the end");
        }
    }
```

What I'm doing wrong?

**Comment by GambaJo** [comment]
I don't know why, but it doesn't work with the share on my local machine. When I create the same share in a VM, it works.
Thx.
